language: generic
sudo: required
services:
- docker

env:
  global:
    - PROJECT_NAME={{ cookiecutter.project_slug }}
    # - Add secure DOCKER_EMAIL
    # - Add secure DOCKER_USER
    # - Add secure DOCKER_PASS
    # - Add secure AZURE_APP_ID
    # - Add secure AZURE_PASSWORD
    # - Add secure AZURE_TENANT_ID
    # - Add secure AZURE_RESOURCE_GROUP
    # - Add secure AZURE_CLUSTER_NAME

before_install:
  - echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin

install:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $TRAVIS_REPO_SLUG:$TAG .

script:
  - make ci.test

after_success:
  - docker push $TRAVIS_REPO_SLUG

deploy:
  # deploy releases branch to their own namespaces
  - provider: script
    script: ./scripts/k8s-deploy-development.sh
    on:
      all_branches: true
      condition: ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^release.*$
  # deploy master to production
  - provider: script
    script: ./scripts/k8s-deploy-production.sh
    on:
      tags: true
