apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: issuer-letsencrypt
spec:
  acme:
    server: https://acme-v01.api.letsencrypt.org/directory
    email: "{{ cookiecutter.email }}"
    privateKeySecretRef:
      name: issuer-letsencrypt
    http01: {}
