apiVersion: v1
kind: Service
metadata:
  name: {{ cookiecutter.k8s_service_name }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: {{ cookiecutter.k8s_service_name }}
