apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{cookiecutter.service_name_lower}}-api.dev.fernandoe.com
      http:
        paths:
          - backend:
              serviceName: {{cookiecutter.service_name_lower}}-api
              servicePort: 80
  tls:
    - hosts:
        - {{cookiecutter.service_name_lower}}-api.dev.fernandoe.com
      secretName: {{cookiecutter.service_name_lower}}-api-dev-fernandoe-com-tls
